/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf8ff",
        "primary": "#24389c",
        "secondary-container": "#33a0fd",
        "inverse-surface": "#2f3037",
        "on-primary-fixed": "#00105c",
        "on-background": "#1a1b22",
        "surface-container-low": "#f4f2fc",
        "on-tertiary-fixed-variant": "#005313",
        "background": "#fbf8ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#cacfff",
        "outline": "#757684",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#bac3ff",
        "primary-fixed": "#dee0ff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e9e7f0",
        "on-primary-fixed-variant": "#293ca0",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e3e1ea",
        "secondary-fixed-dim": "#9ecaff",
        "surface-variant": "#e3e1ea",
        "on-secondary-fixed-variant": "#00497d",
        "surface-tint": "#4355b9",
        "primary-container": "#3f51b5",
        "on-secondary-fixed": "#001d36",
        "surface": "#fbf8ff",
        "inverse-on-surface": "#f2eff9",
        "inverse-primary": "#bac3ff",
        "on-secondary-container": "#00355c",
        "error-container": "#ffdad6",
        "secondary": "#0061a4",
        "tertiary-container": "#00691b",
        "outline-variant": "#c5c5d4",
        "tertiary-fixed": "#94f990",
        "tertiary": "#004e11",
        "on-surface-variant": "#454652",
        "on-surface": "#1a1b22",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d1e4ff",
        "on-tertiary-container": "#83e881",
        "on-tertiary-fixed": "#002204",
        "surface-dim": "#dbd9e2",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#78dc77",
        "surface-container": "#efedf6"
      }
    },
  },
  plugins: [],
}
